name: Regression Tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
  
    env:
      SIM: icarus

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Icarus Verilog
      run: |
        sudo apt install -y iverilog
    
    - name: Run CRC32 test
      run: make -C tb/CRC32
    
    - name: Run Packetizer test
      run: make -C tb/Packetizer
    
    - name: Run SimpleMac test
      run: make -C tb/SimpleMac
    
    - name: Run DataController test
      run: make -C tb/DataController

    - name: Run Serializer test
      run: make -C tb/Serializer

    - name: Rune Deserializer test
      run: make -C tb/Deserializer
